export const CONSTANTS = {
    DEFAULT_RAISED_AMOUNT: '0.00',
    MAX_EMAIL_LENGTH: 255,
    MAX_NAME_LENGTH: 255,
    MAX_WALLET_ADDRESS_LENGTH: 100,
    MAX_TRANSACTION_HASH_LENGTH: 255,
    MAX_SHORT_DESCRIPTION_LENGTH: 500,
    DECIMAL_PRECISION: {
      AMOUNT: 2,
      COIN: 8,
      RATE: 8,
    },
  } as const;